---
name: Release

on:
  push:
    tags:
    - 'v*'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - run: ls
        name: Build
      - uses: ncipollo/release-action@v1
        name: Release
        with:
          artifacts: "bin/*"
          bodyFile: "body.md"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
