---
name: Release

on:
  push:
    tags:
    - 'v*'
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./build.sh
        name: Build
      - uses: ncipollo/release-action@v1
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "bin/*"
          body:  ${{ github.event.head_commit.message }}
